# Config based on https://github.com/IBM-Swift/Package-Builder
# At some point I'll add linux to the matrix here
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required
  # Failing due to `swift package edit` not working
  allow_failures:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - swift package edit BigInt || true
  - swift package edit Graphiti || true
  - swift package edit GraphQL || true
  - swift package edit ProrsumNet || true
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
